version: '3.8'
services:
  node-backend:
    build: ./node-backend
    ports:
      - "3001:3000"
  kundli-service:
    build: ./kundli-service
    ports:
      - "5000:5000"
  web-frontend:
    build: ./web-frontend
    ports:
      - "3000:3000"
  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
